### ISSUE TITLE
Passing R function to parallel for loop

### ISSUE THREAD

**Issue by Patrikios** [tnagler/RcppThread#64]
I wan to plug in R function into `RcppThread` parallel for loop. My attempt crashes all the time, even though I don´t get any compilation error. Here is a small reproducible example.

The .cpp file:
```
#include <RcppThread.h>
// [[Rcpp::plugins(cpp11)]]
// [[Rcpp::depends(RcppThread)]] 

// [[Rcpp::export]]
Rcpp::NumericVector RunFunction2Paral(Rcpp::NumericVector a, Rcpp::Function func){
  
  using namespace RcppThread;
  std::vector<double> b = Rcpp::as< std::vector<double> >(a); 
  
  parallelFor(0, a.size(), [&b, &func] (unsigned int i){
    b[i] = Rcpp::as<double>(func(b[i]));
  });
  
  return Rcpp::NumericVector(b.begin(), b.end());
}
```
The R file:
```
my_r_function <- function(i) { return(i**3) }
x <- as.double(1:10)
RunFunction2Paral(x, my_r_function)
```

Would you be so kind to point out the solution for the problem?

**Comment by tnagler** [comment]
The problem is that you are calling the R API (here: an R function) from multi-threaded code, but R itself is inherently single-threaded. This is also mentioned in the introduction of the [RcppThread paper](https://www.jstatsoft.org/article/view/v097c01):

> To quote from the ‘Writing R Extensions’ manual (R Core Team 2020b,
Section 1.2.1.1): “Calling any of the R API from threaded code is ‘for experts only’”. Using
R’s API from concurrent threads may crash the R session or cause other unexpected behavior.

The main point of RcppThread is to work around these issues for interrupting code and for printing to the R console. Interacting with R functions is orders of magnitude more complicated and I don't see a solution for that any time soon. So, if possible, you should rewrite your R function into C++, otherwise you will need to stick to R-level parallelization.
