### ISSUE TITLE
Problem with synchronization?

### ISSUE THREAD

**Issue by kevin931** [tnagler/RcppThread#66]
I have the following snippet of code that is currently crashing my R. I wonder if it is crashing because multiple threads are accessing/writing at the same time:
```c++

// mu, mu_new, and Sigma_s2 are previously defined and indices are correct.

int m = 2;
int sample_size = 100;
RcppThread::parallelFor(0, 10, [&] (size_t s){
	NumericVector temp = mu[_, s] + mu_new[_, 2];
	double rate = sum(temp)/2+ds;
	double shape = sample_size/2+ds;
	Sigma_s2(s, m) = 1/rgamma(1, shape, 1/rate)(0);
});
```

The inside is well-behaved in a regular for loop. My previous understanding is that reading the same memory is supposed to be safe, and the last line shouldn't be writing to the same place either. So I'm not sure what's the issue here.

**Comment by tnagler** [comment]
The problem is hidden in `rgamma()`, w

https://cran.r-project.org/doc/manuals/R-exts.html

**Comment by tnagler** [comment]
The problem is hidden in the `rgamma()` call. Internally, this hooks back into R and reads/writes the state of R's random number generator, which is not thread safe. As mentioned in the [Writing R extensions manual](https://cran.r-project.org/doc/manuals/R-exts.html#OpenMP-support):

> Calling any of the R API from threaded code is ‘for experts only’ and strongly discouraged. Many functions in the R API modify internal R data structures and might corrupt these data structures if called simultaneously from multiple threads. 

You can instead use [`std::gamma_distribution`](https://en.cppreference.com/w/cpp/numeric/random/gamma_distribution) from the C++ standard library to generate gamma random variables. But be aware that generating independent random number streams requires some extra care, see for example [here](https://michaellindon.github.io/lindonslog/programming/parallel-random-number-generation-trng/index.html) or [here](https://stackoverflow.com/a/4234565). 

Now that I think about it, some facilities for parallel RNG would be nice to have in the library. I might add something someday, but I wouldn't wait for it if I were you ;)

**Comment by kevin931** [comment]
Ahh I see. I didn't think of this as an issue. Thank you so much for linking me to these resources!! And yes, for now I will just stick with single threaded code since I was just toying around with this in one of my projects.
