### ISSUE TITLE
Using RcppArmadillo

### ISSUE THREAD

**Issue by AdaemmerP** [tnagler/RcppThread#75]
Thanks for this great package!

I have written a sample code using `RcppArmadillo`  (see below) which runs as expected. However, I wanted to check if `RcppArmadillo` really does run smoothly with `RcppThread`, or is there anything one has to be aware of?

The code takes two matrices as input. The outer loop iterates in parallel over the rows and the inner loop iterates sequentially over the columns. The cells are modified in the loop. I store the two modified matrices in a list that the function returns. 

The file `mat_rcppthread.cpp`contains: 

```Rcpp
// [[Rcpp::depends(RcppThread)]]
// [[Rcpp::depends("RcppArmadillo")]]
#include <thread>
#include <RcppThread.h>
#include <RcppArmadillo.h>
using namespace Rcpp;
using namespace RcppThread;

// [[Rcpp::export]]
List ParallelMatForExample(arma::mat& x, 
                           arma::mat& y)
{
  // Create list to store the output
  List out(2);
  // Outer loop (over rows in parallel)
  parallelFor(0, x.n_rows, [&x, &y] (unsigned int i) {
    // Inner loop (over columns single-core)
    for (unsigned int j = 0; j < x.n_cols; j++) {
      x(i, j) = i*2;
      y(i, j) = j*2;
    }
  });
  // Convert vectors 
  NumericMatrix xx = wrap(x);
  NumericMatrix yy = wrap(y);
  out[0] = xx;
  out[1] = yy;
  // Return list
  return out;
}
```

Run the following lines in R:

```R
Rcpp::sourceCpp("mat_rcppthread.cpp")

x = matrix(1:1000, ncol = 10)
y = matrix(1:1000, ncol = 10)

ParallelMatForExample(x, y)
```

**Comment by tnagler** [comment]
You should be safe using functionality contained in the Armadillo C++ library, anything that RcppArmadillo provides on top may or may not work. The only way to give a definite answer for the latter is to read and understand the RcppArmadillo source code.  The general principle is:
> No calls to the R API should be made from multi-threaded code.

Accordingly, the snippet should be fine, because
* `arma::mat` assignment (in parallel section) is core Armadillo 
* anything involving `Rcpp::List`, `Rcpp::NumericMatrix`, `Rcpp::wrap()` is outside the parallel section.

**Comment by AdaemmerP** [comment]
Thanks for the reply! This is how I understood it as well and playing around with `Rcpp` objects indeed leads to crashes within `RcppThread`.
